### ISSUE TITLE
Incomplete packet error

### ISSUE THREAD

**Issue by ShiSHcat** [amphp/dns#96]
Next Amp\Dns\DnsException: All query attempts failed for mozilla.cloudflare-dns.com: Unexpected error during resolution: Decode error: Incomplete packet (tried to read 12 bytes from index 0, Unexpected error during resolution: Decode error: Incomplete packet (tried to read 12 bytes from index 0 in /home/shishcat1/redacted/vendor/amphp/dns/lib/Rfc1035StubResolver.php:193
Stack trace:
#0 [internal function]: Amp\Dns\Rfc1035StubResolver->Amp\Dns\{closure}()
PHP 7.4.2 debian

**Comment by kelunik** [comment]
@ShiSHcat Can you reproduce this issue? Which DNS server are you using?

**Comment by ShiSHcat** [comment]
I'm not having this problem anymore.

**Comment by kelunik** [comment]
Thanks for reporting back!

**Comment by karelvasicek** [comment]
I had exactly the same problem (for different domain, of course). The problem was caused by:
- "not accessible" nameserver defined (as first server) in `/etc/resolv.conf`. There was some problems with DNS cache (the actual server _was_ accessible, but somewhat _refused_ connections) what resulted in following output (the output was shown immediately, so there was **no timeout**)
  ```
  host www.google.com nonworking.dns.server.ip
  ;; communications error to nonworking.dns.server.ip#53: connection refused
  ;; communications error to nonworking.dns.server.ip#53: connection refused
  ;; no servers could be reached
  ```
- under "standard" circumstances, connection to the nameserver times out ((the output was shown incrementally with considerable delay between each attempt)
  ```
  host www.google.com nonworking.dns.server.ip
  ;; communications error to nonworking.dns.server.ip#53: timed out
  ;; communications error to nonworking.dns.server.ip#53: timed out
  ;; no servers could be reached
  ```
- so the connection seems to be considered established and it does not timeout at https://github.com/amphp/dns/blob/c2bddbd80b3b80030cd7d3af591414e0dbc7a272/lib/Internal/Socket.php#L171
- https://github.com/amphp/dns/blob/c2bddbd80b3b80030cd7d3af591414e0dbc7a272/lib/Rfc1035StubResolver.php#L331 throws `UnexpectedValueException ('Decode error: Incomplete packet (tried to read 12 bytes from index 0')` that is received from `vendor/daverandom/libdns/src/Decoder/Decoder.php:121` and is converted to `DnsException` by https://github.com/amphp/dns/blob/c2bddbd80b3b80030cd7d3af591414e0dbc7a272/lib/Internal/Socket.php#L89
- it seems to start working by replacing `$response = yield $socket->ask($question, $this->config->getTimeout());` with following code, but I'm totally unsure if it's correct or not especially considering my poor library and async-logic knowledge - f.ex. if another unintended `DnsException` isn't newly caught, how the socket should be closed etc. In addition, potential infinite loop (when all servers are not accessible) must be secured. Thus I'm not creating PR, it's just a concept how the issue could be fixed.
  ```
                    try {
                        /** @var Message $response */
                        $response = yield $socket->ask($question, $this->config->getTimeout());
                    } catch (DnsException $e) {
                        if ($protocol === "udp") {
                            Loop::defer(function () use ($socket, $uri) {
                                unset($this->sockets[$uri]);
                                $socket->close();
                            });

                            $uri = $protocol . "://" . $nameservers[++$attempt % $nameserversCount];
                            $socket = yield $this->getSocket($uri);

                            continue;
                        }
                    }
  ```
